version: "3.9"
name: gender-classifier

services:
  api:
    container_name: "api"
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend:/usr/src/app

  web:
    container_name: "web"
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
       - ./data/certbot/conf:/etc/letsencrypt
       - ./data/certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

 

  # nginx:
  #   container_name: "nginx"
  #   build: ./docker/nginx
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./frontend/build:/usr/share/nginx/html
  #     - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - api
  #     - web