version: "3.9"
name: gender-classifier

services:
  fastapi:
    container_name: "fastapi"
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend:/usr/src/app
      - ./certs:/etc/letsencrypt
    

  web:
    container_name: "web"
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./frontend:/usr/src/app
      - .:/letsencrypt # for certboot challenges
      - ./certs:/etc/letsencrypt # for letsencrypt certificates
      - ./etc/ssl/certs:/etc/ssl/certs
    links:
      - "fastapi" 
  
  certbot:
    container_name: "certbot"
    image: certbot/certbot
    volumes:
      - .:/letsencrypt
      - ./certs:/etc/letsencrypt
    command: certonly --webroot -w /letsencrypt -d ${DOMAIN1} -d ${DOMAIN2} --force-renew --agree-tos --email ${EMAIL}
    depends_on:
      - fastapi
      - web