version: "3.9"
name: gender-classifier

services:
  api:
    container_name: "api"
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./backend:/usr/src/app

  web:
    container_name: "web"
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ${PWD}:/letsencrypt
      - ${PWD}/certs:/etc/letsencrypt