version: "3.9"
name: gender-classifier

services:
  api:
    container_name: "api"
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./backend:/usr/src/app

  web:
    container_name: "web"
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - ./:/letsencrypt:ro
      - ./certs:/etc/nginx/ssl/:ro
#    command: openssl req -nodes -new -x509 -subj "/CN=localhost" -keyout ${PWD}/website.key -out ${PWD}/certs/website.crt


  certbot:
    container_name: "certbot"
    image: certbot/certbot
    volumes:
      - .:/letsencrypt:rw
      - ./certs:/etc/letsencrypt:rw
    #command: certonly --webroot --agree-tos --renew-by-default --text --email pfpimenta@gmail.com -w /letsencrypt -d app1.ouicodedata.com
    command: certonly --webroot --non-interactive --staging --agree-tos --email pfpimenta@gmail.com -w /letsencrypt -d app1.ouicodedata.com 
    #command:  certonly -d app1.ouicodedata.com
    depends_on:
      - api
      - web