version: "3.9"
name: gender-classifier

services:
  api:
    container_name: "api"
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./backend:/usr/src/app

  web:
    container_name: "web"
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - .:/letsencrypt # for certboot challenges
      - ./certs:/etc/letsencrypt # for letsencrypt certificates
  
  # certbot:
  #   container_name: "certbot"
  #   image: certbot/certbot
  #   volumes:
  #     - .:/letsencrypt
  #     - ./certs:/etc/letsencrypt
  #   #command: certonly --webroot --agree-tos --renew-by-default --text --email pfpimenta@gmail.com -w /letsencrypt -d app1.ouicodedata.com
  #   command: certonly --webroot --non-interactive --preferred-challenges http-01 --server https://acme-v02.api.letsencrypt.org/directory --staging --agree-tos --email pfpimenta@gmail.com -w /letsencrypt -d app1.ouicodedata.com -d www.app1.ouicodedata.com 
  #   #command:  certonly -d app1.ouicodedata.com
  #   depends_on:
  #     - api
  #     - web