version: "3.9"
name: gender-classifier

services:
  fastapi:
    container_name: "fastapi"
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend:/usr/src/app
      - ./certbot/www:/var/www/certbot # for letsencrypt certificates

  web:
    container_name: "web"
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./frontend:/usr/src/app
      - ./certbot/conf:/etc/letsencrypt # for certboot challenges
      - ./certbot/www:/var/www/certbot # for letsencrypt certificates
      #- ./etc/ssl/certs:/etc/ssl/certs
    #links:
      #- "fastapi" 
  
  #certbot:
  #  container_name: "certbot"
  #  image: certbot/certbot
  #  volumes:
  #    - ./certbot/conf:/etc/letsencrypt # for certboot challenges
  #    - ./certbot/www:/var/www/certbot # for letsencrypt certificates
  #  command: certonly --webroot -w /var/www/certbot -d ${DOMAIN1} --force-renew --agree-tos --email ${EMAIL}
    #depends_on:
      #- fastapi
    #  - web