version: "3.9"
name: gender-classifier

services:
  api:
    container_name: "api"
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./backend:/usr/src/app

  web:
    container_name: "web"
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - ${PWD}:/letsencrypt
      - ${PWD}/certs:/etc/letsencrypt

  certbot:
    container_name: "certbot"
    image: certbot/certbot:1.8.0
    volumes:
      - ${PWD}:/letsencrypt
      - ${PWD}/certs:/etc/letsencrypt
    command: certboot certonly --webroot --agree-tos --renew-by-default \
            --preferred-challenges http-01 --server https://acme-v02.api.letsencrypt.org/directory --text --email pfpimenta@gmail.com -w /letsencrypt \
            -d app1.ouicodedata.com
    depends_on:
      - api
      - web