version: "3.9"
name: gender-classifier

services:
  api:
    container_name: "api"
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./backend:/usr/src/app

  web:
    container_name: "web"
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    ports:
      - "80:80"
      - 443:443
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - ./docker/nginx/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    restart: always
  
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw



  # nginx:
  #   container_name: "nginx"
  #   build: ./docker/nginx
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./frontend/build:/usr/share/nginx/html
  #     - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - api
  #     - web